{
 "title": "Linux Server",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{job=\"Linux Servers\"} / node_memory_MemTotal_bytes{job=\"Linux Servers\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk IO Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"Linux Servers\"}[5m])"
    }
   ]
  },
  {
   "title": "CPU Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{job=\"Linux Servers\",mode=\"system\"}[5m])) * 100",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{job=\"Linux Servers\",mode=\"user\"}[5m])) * 100",
     "legendFormat": "user: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"Linux Servers\", device=\"ens5\"}[5m])"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"Linux Servers\", device=\"ens5\"}[5m]) * -1"
    }
   ]
  },
  {
   "title": "Linux Server Up",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"Linux Servers\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}