{
 "title": "Servers",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info{job=\"nodes\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{job=\"nodes\"} / node_memory_MemTotal_bytes{job=\"nodes\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk IO Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"nodes\"}[5m])"
    }
   ]
  },
  {
   "title": "load for $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"nodes\", device=\"ens5\"}[5m])"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"nodes\", device=\"ens5\"}[5m]) * -1"
    }
   ]
  },
  {
   "title": "CPU Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (hostname) (rate(node_cpu_seconds_total{job=\"nodes\",mode=\"system\"}[5m])) * 100",
     "legendFormat": "system: {{hostname}}"
    },
    {
     "expr": "sum by (hostname) (rate(node_cpu_seconds_total{job=\"nodes\",mode=\"user\"}[5m])) * 100",
     "legendFormat": "user: {{hostname}}"
    }
   ]
  },
  {
   "title": "Linux Server Up",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"nodes\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}