#
#
#
- name: common tasks for all hosts
  hosts: all
  become: yes
  roles:
    - common
    - node_exporter

- name: configure consul servers
  hosts: consul_servers
  become: yes
  roles:
    - consul

- name: configure web servers
  hosts: web_servers
  become: yes
  roles:
    - nginx

- name: configure log servers
  hosts: log_servers
  become: yes
  roles:
    - elasticsearch

- name: configure prometheus servers
  hosts: prom_servers
  become: yes
  roles:
    - alertmanager
    - prometheus
    - grafana
    - nginx
    - prom_nginx_config

- name: post consul actions
  hosts: consul_servers
  become: yes
  roles:
    - post_consul