#
#
#
- name: common tasks for all hosts
  hosts: all
  become: yes
  roles:
    - common
    - node_exporter

- name: configure consul servers
  hosts: consul_servers
  become: yes
  roles:
    - consul

- name: configure prometheus servers
  hosts: prom_servers
  become: yes
  roles:
    - alertmanager
    - prometheus
    - grafana
    - nginx
