---
- name: common tasks for all hosts
  hosts: all
  become: yes
  roles:
    - common
    - node_exporter

- name: configure consul servers
  hosts: consul_servers
  become: yes
  roles:
    - consul

- name: configure web servers
  hosts: web_servers
  become: yes
  roles:
    - nginx

- name: configure log data servers
  hosts: elk_data_servers
  become: yes
  roles:
    - elasticsearch
  vars:
    es_role: data

- name: configure log master servers
  hosts: elk_master_servers
  become: yes
  roles:
    - elasticsearch
    - kibana
  vars:
    es_role: master
#    - logstash

- name: configure kafka servers
  hosts: kafka_servers
  become: yes
  roles:
    - kafka

- name: configure prometheus servers
  hosts: prom_servers
  become: yes
  roles:
    - alertmanager
    - prometheus
    - grafana
    - nginx
    - prom_nginx_config

- name: post consul actions
  hosts: consul_servers
  become: yes
  roles:
    - post_consul

- name: configure consul on prometheus servers
  hosts: prom_servers
  become: yes
  roles:
    - consul_agent
    - prom_consul

- name: configure consul on kafka servers
  hosts: kafka_servers
  become: yes
  roles:
    - consul_agent

- name: app server
  hosts: app_servers
  become: yes
  roles:
    - consul_agent
    - java

#- name: post everything
#  hosts: all
#  become: yes
#  roles:
#    - filebeat
...
