security.protocol=SSL
ssl.truststore.location=/opt/kafka/broker.truststore.p12
ssl.truststore.password=changeit
# kafka-topics.sh --list --bootstrap-server=kafka-00.podspace.internal:9094 --command-config=client-ssl.properties
